import{R as u,S as f,N as p,P as b,A as m,a as y}from"./assets/vendor-CIT6v5q3.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const g="https://deserts-store.b.goit.study/api/feedbacks?limit=10",r={list:document.querySelector(".feedback-list"),loader:document.querySelector(".feedback-loader-wrap"),prevBtn:document.querySelector(".feedback-nav-prev"),nextBtn:document.querySelector(".feedback-nav-next"),bottom:document.querySelector(".feedback-bottom"),pagination:document.querySelector(".feedback-pagination")};let c=null;h();async function h(){if(r.list)try{const e=await w();k(e),r.list.hidden=!1,r.prevBtn.hidden=!1,r.nextBtn.hidden=!1,r.bottom.hidden=!1,S(),q()}catch(e){r.list.hidden=!1,r.list.innerHTML='<li class="feedback-message">Не вдалося завантажити відгуки. Спробуйте оновити сторінку.</li>',console.error(e)}finally{r.loader.hidden=!0}}async function w(){const e=await fetch(g);if(!e.ok)throw new Error(`Feedback request failed: ${e.status}`);return((await e.json()).feedbacks||[]).slice(0,10)}function k(e){r.list.innerHTML=e.map(v).join("")}function v({_id:e,rate:n,description:s,author:i}){return`
    <li class="swiper-slide feedback-item">
      <article class="feedback-card">
        <div
          class="feedback-rating"
          data-rating="${Number(n)}"
          aria-label="Оцінка ${Number(n)} з 5"
        ></div>
        <p class="feedback-review">"${s}"</p>
        <h3 class="feedback-author">${i}</h3>
      </article>
    </li>
  `}function S(){document.querySelectorAll(".feedback-rating").forEach(e=>{new u(e,{score:Number(e.dataset.rating),readOnly:!0,halfShow:!0,starType:"i",space:!1,hints:["1","2","3","4","5"]}).init()})}function q(){c&&c.destroy(!0,!0),c=new f(".feedback-swiper",{modules:[p,b,m],slidesPerView:1,spaceBetween:24,speed:500,grabCursor:!0,navigation:{prevEl:r.prevBtn,nextEl:r.nextBtn},pagination:{el:r.pagination,clickable:!0,bulletClass:"feedback-pagination-bullet",bulletActiveClass:"feedback-pagination-bullet-active",renderBullet(e,n){return`<button class="${n}" type="button" aria-label="Перейти до відгуку ${e+1}"></button>`}},a11y:{prevSlideMessage:"Попередній відгук",nextSlideMessage:"Наступний відгук",paginationBulletMessage:"Перейти до відгуку {{index}}"},breakpoints:{768:{slidesPerView:3,spaceBetween:22},1440:{slidesPerView:3,spaceBetween:24}}})}const l=document.querySelector(".faq-accordion");l&&new y(l,{duration:400,showMultiple:!1,openOnInit:[]});const d=document.querySelector("[data-current-year]");d&&(d.textContent=new Date().getFullYear());
//# sourceMappingURL=index.js.map
